config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

   get '/sign-up' => 'registrations#new', as: :signup
   post '/sign-up' => 'registrations#create'
   get '/sign-in' => 'authentication#new', as: :signin
   post '/login' => 'authentication#create'
   get '/sign-out' => 'authentication#destroy', as: :signout
   resources :registrations, only: [:new, :create]
   resources :courses
   resources :users

end

app/models/course.rb
class Course < ActiveRecord::Base
  # def course_time
  #   if Course.day?
  #     course == "Day"
  #   else
  #     course == "Night"
  #   end
  # end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  validates :user_name, presence: true, uniqueness:true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    User.find_by(id: session[:user_id])
  end

  # def course_time(course)
  #   if course.day?
  #     course_time == "Day"
  #   else
  #     course_time == "Night"
  #   end
  # end

  helper_method :current_user

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def new
    @user = User.new
  end


  def create
    user = User.find_by(user_name: (params[:user_name]))
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      @sign_in_error = "Username/password combination is invalid"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.create(course_params)
    if @course.save
      redirect_to course_path(@course)
    else
      render :new
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to course_path(@course)
    else
      render :edit
    end
  end

  def delete
    @course = Course.find(params[:id])
  end

  def destroy
    @course = Course.find(params[:id])
    if @course.destroy
      redirect_to courses_path, notice: 'Course sucessfully deleted'
    end
  end





  private
  def course_params
    params.require(:course).permit(:title, :day)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:user_name, :password, :password_confirmation))
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to users_path
    end
  end


  private
  def user_params
    params.require(:user).permit(:user_name)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<%= form_tag '/login' %>

<%= label_tag :user_name %>
<%= text_field_tag :user_name %>

<%= label_tag :password %>
<%= password_field_tag :password %>

<%= submit_tag 'Login' %>

app/views/authentications/new.html.erb
<%= form_tag '/signup' %>

<%= label_tag :user_name %>
<%= text_field_tag :user_name %>

<%= label_tag :password %>
<%= password_field_tag :password %>

<%= submit_tag 'Login' %>

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :day %>
  <%= f.check_box :day %>
</p>
<p>
  <%= f.submit %>
  <%= link_to "Cancel", root_path %>
</p>
<% end %>

app/views/courses/edit.html.erb
<h1> Edit Course </h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<% if notice %>
<p> <%= notice %> </p>
<% end %>

<p><%= link_to "Home", root_path %></p>

<p>Courses</p>


<%= link_to "Add new course", new_course_path %>

<table>
  <thead>
    <tr>
      <th>Course Title</th>
      <th>Day or Night</th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
    <tr>
      <th><%= link_to course.title, course_path(course) %></th>
      <% if course.day? %>
        <th>Day</th>
        <% else %>
        <th>Night</th>
      <% end %>
      <th><%= link_to "Edit", edit_course_path(course) %></th>
      <th><%= link_to "Delete", course_path(course), method: 'delete' %></th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1>Add a new course </h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<h1>Course Information: </h1>
<p><span>Course title: </span><span> <%= @course.title %> </p>
<p>
  <span>Day or night: </span>

  <% if @course.day? %>
    <span>Day</span>
    <% else %>
    <span>Night</span>
  <% end %>
</p>


  <%= link_to "Home", root_path %>
  <%= link_to "Delete", course_path(@course), method: 'delete' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CameronWeek7</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
  <p>
    <span>
      <%= current_user.user_name %> |
      <%= link_to "Logout", signout_path %>
    </span>
    <% else %>
    <span>
      <%= link_to "Login", signin_path %> |
      <%= link_to "Register", signup_path %>
    </span>
  </p>

  <% end %>

<p>
<%= yield %>
</p>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= f.label :user_name %>
<%= f.text_field :user_name %>

<%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit user </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<p><%= link_to "Home", root_path %></p>

<h1>Users</h1>

<%= link_to "Add new user", new_user_path %>

<table>
  <thead>
    <tr>
      <th>Username</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user.user_name %>
        </td>
        <td>
          <%= link_to 'Edit', edit_user_path(user) %>
        </td>
        <td>
          <%= link_to "Delete", user_path(user), method: 'delete' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Add user </h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>User information </h1>
<p>Username: <%= @user.user_name %></p>



<%= link_to "User Home", users_path %>

app/views/welcome/index.html.erb
<% if current_user %>

<%= link_to "Users", users_path %>
<%= link_to "Courses", courses_path %>

<% end %>